# Generated by Django 3.0.2 on 2020-01-28 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Farhan',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=255)),
                ('Value', models.CharField(default='', max_length=255)),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateField(blank=True)),
                ('Time', models.DateField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255)),
                ('Description', models.CharField(default='No Issues', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='FarhanFamilySuperFund',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=255)),
                ('Value', models.CharField(default='', max_length=255)),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateField(blank=True)),
                ('Time', models.DateField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255)),
                ('Description', models.CharField(default='No Issues', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Nadia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=255)),
                ('Value', models.CharField(default='', max_length=255)),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateField(blank=True)),
                ('Time', models.DateField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255)),
                ('Description', models.CharField(default='No Issues', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Ongie',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=255)),
                ('Value', models.CharField(default='', max_length=255)),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateField(blank=True)),
                ('Time', models.DateField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255)),
                ('Description', models.CharField(default='No Issues', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OrangeTrust',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Title', models.CharField(default='', max_length=255)),
                ('Value', models.CharField(default='', max_length=255)),
                ('Image', models.FileField(blank=True, upload_to='')),
                ('Date', models.DateField(blank=True)),
                ('Time', models.DateField(auto_now_add=True)),
                ('Category', models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255)),
                ('Description', models.CharField(default='No Issues', max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
