# Generated by Django 3.0.2 on 2020-01-25 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='desktops',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='price',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='status',
        ),
        migrations.RemoveField(
            model_name='desktops',
            name='type',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='price',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='status',
        ),
        migrations.RemoveField(
            model_name='laptops',
            name='type',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='issues',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='price',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='status',
        ),
        migrations.RemoveField(
            model_name='mobiles',
            name='type',
        ),
        migrations.AddField(
            model_name='desktops',
            name='Category',
            field=models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='desktops',
            name='Description',
            field=models.CharField(default='No Issues', max_length=255),
        ),
        migrations.AddField(
            model_name='desktops',
            name='Title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='desktops',
            name='Value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laptops',
            name='Category',
            field=models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='laptops',
            name='Description',
            field=models.CharField(default='No Issues', max_length=255),
        ),
        migrations.AddField(
            model_name='laptops',
            name='Title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='laptops',
            name='Value',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='Category',
            field=models.CharField(choices=[('Work', 'Work'), ('Charity', 'Charity'), ('Tax', 'Tax'), ('Water', 'Water'), ('Council', 'Council'), ('Insurance', 'Insurance'), ('Land Tax', 'Land Tax'), ('Repairs', 'Repairs'), ('Sundry', 'Sundry'), ('Interest', 'Interest'), ('Garden', 'Garden'), ('Property Agent', 'Property Agent'), ('Borrowing', ' Borrowing'), ('Depreciation', 'Depreciation'), ('Pest', 'Pest'), ('Advertising', 'Advertising'), (' Stationary', 'Stationary'), ('Telephone', 'Telephone'), ('Postage', 'Postage'), (' Electicity', 'Electicity'), ('Gas', 'Gas'), ('Conveyancing', 'Conveyancing')], default='None', max_length=255),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='Description',
            field=models.CharField(default='No Issues', max_length=255),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='Title',
            field=models.CharField(default='', max_length=255),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='Value',
            field=models.CharField(default='', max_length=255),
        ),
    ]
