# Generated by Django 3.0.2 on 2020-01-25 11:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0002_auto_20200125_1057'),
    ]

    operations = [
        migrations.AddField(
            model_name='desktops',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='laptops',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='mobiles',
            name='Image',
            field=models.FileField(blank=True, upload_to=''),
        ),
    ]
