# Generated by Django 3.0.2 on 2020-01-25 11:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0003_auto_20200125_1112'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktops',
            old_name='Title',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='Title',
            new_name='type',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='Title',
            new_name='type',
        ),
    ]
