# Generated by Django 3.0.2 on 2020-01-25 11:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Expenses', '0004_auto_20200125_1135'),
    ]

    operations = [
        migrations.RenameField(
            model_name='desktops',
            old_name='type',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='laptops',
            old_name='type',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='mobiles',
            old_name='type',
            new_name='Title',
        ),
    ]
